"""empty message

Revision ID: d18f9edc66b7
Revises: 134a06c1a65a
Create Date: 2025-12-19 17:45:29.720683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18f9edc66b7'
down_revision: Union[str, Sequence[str], None] = '134a06c1a65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Carts', ['id'])
    op.create_unique_constraint(None, 'Orders', ['id'])
    op.create_unique_constraint(None, 'Products', ['id'])
    op.create_unique_constraint(None, 'Users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Products', type_='unique')
    op.drop_constraint(None, 'Orders', type_='unique')
    op.drop_constraint(None, 'Carts', type_='unique')
    # ### end Alembic commands ###
