"""empty message

Revision ID: dc7cd538cba7
Revises: d18f9edc66b7
Create Date: 2025-12-20 10:47:36.157133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7cd538cba7'
down_revision: Union[str, Sequence[str], None] = 'd18f9edc66b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Cart_Products', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('Cart_Products', 'cart_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('Cart_Products', 'product_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_Cart_Products_id'), 'Cart_Products', ['id'], unique=True)
    op.alter_column('Carts', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('Order_Products', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('Order_Products', 'product_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_Order_Products_id'), 'Order_Products', ['id'], unique=True)
    op.alter_column('Orders', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('Products', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('Products_id_key'), 'Products', type_='unique')
    op.create_index(op.f('ix_Products_id'), 'Products', ['id'], unique=True)
    op.alter_column('Users', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('Users_id_key'), 'Users', type_='unique')
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.create_unique_constraint(op.f('Users_id_key'), 'Users', ['id'], postgresql_nulls_not_distinct=False)
    op.alter_column('Users', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_Products_id'), table_name='Products')
    op.create_unique_constraint(op.f('Products_id_key'), 'Products', ['id'], postgresql_nulls_not_distinct=False)
    op.alter_column('Products', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('Orders', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_Order_Products_id'), table_name='Order_Products')
    op.alter_column('Order_Products', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('Order_Products', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('Carts', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_Cart_Products_id'), table_name='Cart_Products')
    op.alter_column('Cart_Products', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('Cart_Products', 'cart_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('Cart_Products', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
